### Crear un alumno
POST http://localhost:3000/alumnos
Content-Type: application/json

{
  "nombre": "Pedro",
  "notas": [7, 8, 9]
}

### Listar todos los alumnos
GET http://localhost:3000/alumnos

### Consultar un alumno específico
GET http://localhost:3000/alumnos/Pedro

### Modificar un alumno
PUT http://localhost:3000/alumnos/Pedro
Content-Type: application/json

{
  "notas": [5, 6, 7]
}
